os:
  shellFunctionsFile: /Users/I529035/.zshaliases
gui:
  shortTimeFormat: 03:04
  nerdFontsVersion: "3"
  # tokyo night moon theme
  theme:
    activeBorderColor:
      - "#ff966c"
      - "bold"
    inactiveBorderColor:
      - "#589ed7"
    searchingActiveBorderColor:
      - "#ff966c"
      - "bold"
    optionsTextColor:
      - "#82aaff"
    selectedLineBgColor:
      - "#2d3f76"
    cherryPickedCommitFgColor:
      - "#82aaff"
    cherryPickedCommitBgColor:
      - "#c099ff"
    markedBaseCommitFgColor:
      - "#82aaff"
    markedBaseCommitBgColor:
      - "#ffc777"
    unstagedChangesColor:
      - "#c53b53"
    defaultFgColor:
      - "#c8d3f5"
git:
  pagers:
    - pager: delta --syntax-theme tokyonight_moon --paging=never --diff-so-fancy --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
customCommands:
  - key: "<c-d>"
    command: 'MAIN_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed "s@^refs/remotes/origin/@@" || (git show-ref --verify --quiet refs/remotes/origin/main && echo "main") || echo "master"); git diff origin/$MAIN_BRANCH...HEAD'
    description: "Show diff from main branch to current branch"
    context: localBranches
    output: terminal
  - key: "n"
    # command: 'git commit -m "$(git diff --staged | claude --model haiku --print "Generate a concise git commit message for these staged changes. Output only the commit message, no explanation. Output the plain text only without any backticks. Also do not include the ticket id. Stick to the Conventional Commits format.")"'
    command: 'claude --model haiku --print "commit the staged files. If no files are staged, commit all changes"'
    description: "Use claude to create a commit from the currently staged file changes."
    context: files
    output: "log"
  - key: "<c-p>"
    command: 'claude --model haiku "create a pull request"'
    description: "Use claude to create a pull request (interactive)."
    context: localBranches
    output: terminal
  - key: "C"
    command: "gh poi"
    loadingText: "Cleaning merged branches..."
    description: "Remove merged branches"
    context: localBranches
  - key: "t"
    command: "gcob {{.Form.TicketId}} {{.Form.BranchName}}"
    loadingText: "Creating branch from Jira ticket..."
    description: "New branch based on jira ticket"
    context: localBranches
    prompts:
      - type: "menuFromCommand"
        title: "Which ticket do you want to use?"
        key: "TicketId"
        command: "jira issue list --plain --no-headers --columns key,summary -s~Done -s~Rejected -amaik.schwan@leanix.net"
        filter: "^(?P<key>[A-Z]+-[0-9]+)\\s+(?P<value>.*)"
        labelFormat: "{{ .key }}: {{ .value }}"
        valueFormat: "{{ .key }}"
      - type: "input"
        title: "Enter branch description:"
        key: "BranchName"
        initialValue: ""
