os:
  shellFunctionsFile: /Users/I529035/.zshaliases
git:
  paging:
    externalDiffCommand: difft --color=always
gui:
  shortTimeFormat: 03:04
  nerdFontsVersion: "3"

  # tokyo night moon theme
  theme:
    activeBorderColor:
      - "#ff966c"
      - "bold"
    inactiveBorderColor:
      - "#589ed7"
    searchingActiveBorderColor:
      - "#ff966c"
      - "bold"
    optionsTextColor:
      - "#82aaff"
    selectedLineBgColor:
      - "#2d3f76"
    cherryPickedCommitFgColor:
      - "#82aaff"
    cherryPickedCommitBgColor:
      - "#c099ff"
    markedBaseCommitFgColor:
      - "#82aaff"
    markedBaseCommitBgColor:
      - "#ffc777"
    unstagedChangesColor:
      - "#c53b53"
    defaultFgColor:
      - "#c8d3f5"

customCommands:
  # - key: "n"
  #   command: 'git commit -m "$(git diff --staged | mods -R commit)"'
  #   description: "Use mods and AI to create a commit from the currently staged file changes."
  #   context: files
  #   output: "log"
  - key: "n"
    description: "Use mods and AI to create a commit from the currently staged file changes."
    command: "git commit -m {{.Form.Message | quote}}"
    context: "files"
    output: "log"
    prompts:
      - type: "menuFromCommand"
        title: "commit message"
        key: "Message"
        command: "aicommitmsg"
