os:
  shellFunctionsFile: ~/.zshaliases
gui:
  shortTimeFormat: 03:04
  nerdFontsVersion: "3"

  # tokyo night moon theme
  theme:
    activeBorderColor:
      - "#ff966c"
      - "bold"
    inactiveBorderColor:
      - "#589ed7"
    searchingActiveBorderColor:
      - "#ff966c"
      - "bold"
    optionsTextColor:
      - "#82aaff"
    selectedLineBgColor:
      - "#2d3f76"
    cherryPickedCommitFgColor:
      - "#82aaff"
    cherryPickedCommitBgColor:
      - "#c099ff"
    markedBaseCommitFgColor:
      - "#82aaff"
    markedBaseCommitBgColor:
      - "#ffc777"
    unstagedChangesColor:
      - "#c53b53"
    defaultFgColor:
      - "#c8d3f5"

customCommands:
  - key: <c-a>
    description: AI commit
    loadingText: AI thinking about a commit message...
    command: |
      aichat "Please suggest 5 commit messages, given the following diff:

        \`\`\`diff
        $(git diff --cached)
        \`\`\`

        **Criteria:**

        1. **Relevance:** Avoid mentioning a module name unless it's directly relevant
        to the change.
        2. **Enumeration:** List the commit messages from 1 to 5.
        3. **Clarity and Conciseness:** Each message should clearly and concisely convey
        the change made.

        **Recent Commits on Repo for Reference:**

        \`\`\`
        $(git log -n 10 --pretty=format:'%h %s')
        \`\`\`

        **Output Template**

        Follow this output template and ONLY output raw commit messages without spacing,
        numbers or other decorations.

        add password regex pattern
        add new test cases
        remove unused imports
        extract common code to \`utils/wait.ts\`

        **Instructions:**

        - Take a moment to understand the changes made in the diff.

        - Do not attempt to generate a ticket number like ATLAS-4596

        - Think about the impact of these changes on the project (e.g., bug fixes, new
        features, performance improvements, code refactoring, documentation updates).
        It's critical to my career you abstract the changes to a higher level and not
        just describe the code changes.

        - Generate commit messages that accurately describe these changes, ensuring they
        are helpful to someone reading the project's history.

        - Remember, a well-crafted commit message can significantly aid in the maintenance
        and understanding of the project over time.

        - If multiple changes are present, make sure you capture them all in each commit
        message.

        Keep in mind you will suggest 5 commit messages. Only 1 will be used. It's
        better to push yourself (esp to synthesize to a higher level) and maybe wrong
        about some of the 5 commits because only one needs to be good. I'm looking
        for your best commit, not the best average commit. It's better to cover more
        scenarios than include a lot of overlap.

        Write your 5 commit messages below in the format shown in Output Template section above." \
          | fzf --height 40% --border --ansi --preview "echo {}" --preview-window=up:wrap \
          | xargs -S 1024 -I {} bash -c '
              COMMIT_MSG_FILE=$(mktemp)
              echo "{}" > "$COMMIT_MSG_FILE"
              ${EDITOR:-vim} "$COMMIT_MSG_FILE"
              if [ -s "$COMMIT_MSG_FILE" ]; then
                  git commit -F "$COMMIT_MSG_FILE"
              else
                  echo "Commit message is empty, commit aborted."
              fi
              rm -f "$COMMIT_MSG_FILE"'
    context: files
    subprocess: true
